services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
#    command: gunicorn projeto.wsgi:application --bind 0.0.0.0:80
#    volumes:
#      - ./:/app
    ports:
      - "80:80"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
